// <auto-generated />
using System;
using DataProvisioning.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataProvisioning.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324170905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataProvisioning.Domain.Entities.AccessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justification");

                    b.Property<int?>("PolicyGroupId")
                        .HasColumnType("int")
                        .HasColumnName("policy_group_id");

                    b.Property<string>("RequestedRlsFilters")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requested_rls_filters");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("PolicyGroupId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("UserId");

                    b.ToTable("access_requests", (string)null);
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.AssetPolicyColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("column_name");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("is_hidden");

                    b.Property<int>("PolicyGroupId")
                        .HasColumnType("int")
                        .HasColumnName("policy_group_id");

                    b.HasKey("Id");

                    b.HasIndex("PolicyGroupId");

                    b.ToTable("asset_policy_columns", (string)null);
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.AssetPolicyCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("column_name");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("operator");

                    b.Property<int>("PolicyGroupId")
                        .HasColumnType("int")
                        .HasColumnName("policy_group_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("PolicyGroupId");

                    b.ToTable("asset_policy_conditions", (string)null);
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.AssetPolicyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("OwnerId");

                    b.ToTable("asset_policy_groups", (string)null);
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("OwnerGroupId")
                        .HasColumnType("int")
                        .HasColumnName("owner_group_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerGroupId");

                    b.ToTable("datasets", (string)null);
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.DatasetColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_type");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("definition");

                    b.Property<bool>("IsPii")
                        .HasColumnType("bit")
                        .HasColumnName("is_pii");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("SampleData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sample_data");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("columns", (string)null);
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.VirtualGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("virtual_groups", (string)null);
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.VirtualGroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("added_at");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("virtual_group_members", (string)null);
                });

            modelBuilder.Entity("report_datasets", b =>
                {
                    b.Property<int>("dataset_id")
                        .HasColumnType("int");

                    b.Property<int>("report_id")
                        .HasColumnType("int");

                    b.HasKey("dataset_id", "report_id");

                    b.HasIndex("report_id");

                    b.ToTable("report_datasets");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.AccessRequest", b =>
                {
                    b.HasOne("DataProvisioning.Domain.Entities.Dataset", "Dataset")
                        .WithMany("AccessRequests")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataProvisioning.Domain.Entities.AssetPolicyGroup", "PolicyGroup")
                        .WithMany("AccessRequests")
                        .HasForeignKey("PolicyGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataProvisioning.Domain.Entities.User", "ReviewedBy")
                        .WithMany("ReviewedRequests")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataProvisioning.Domain.Entities.User", "User")
                        .WithMany("AccessRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("PolicyGroup");

                    b.Navigation("ReviewedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.AssetPolicyColumn", b =>
                {
                    b.HasOne("DataProvisioning.Domain.Entities.AssetPolicyGroup", "PolicyGroup")
                        .WithMany("HiddenColumns")
                        .HasForeignKey("PolicyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyGroup");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.AssetPolicyCondition", b =>
                {
                    b.HasOne("DataProvisioning.Domain.Entities.AssetPolicyGroup", "PolicyGroup")
                        .WithMany("Conditions")
                        .HasForeignKey("PolicyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyGroup");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.AssetPolicyGroup", b =>
                {
                    b.HasOne("DataProvisioning.Domain.Entities.Dataset", "Dataset")
                        .WithMany("PolicyGroups")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataProvisioning.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dataset");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.Dataset", b =>
                {
                    b.HasOne("DataProvisioning.Domain.Entities.VirtualGroup", "OwnerGroup")
                        .WithMany("Datasets")
                        .HasForeignKey("OwnerGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerGroup");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.DatasetColumn", b =>
                {
                    b.HasOne("DataProvisioning.Domain.Entities.Dataset", "Dataset")
                        .WithMany("Columns")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.VirtualGroup", b =>
                {
                    b.HasOne("DataProvisioning.Domain.Entities.User", "Owner")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.VirtualGroupMember", b =>
                {
                    b.HasOne("DataProvisioning.Domain.Entities.VirtualGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataProvisioning.Domain.Entities.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("report_datasets", b =>
                {
                    b.HasOne("DataProvisioning.Domain.Entities.Dataset", null)
                        .WithMany()
                        .HasForeignKey("dataset_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataProvisioning.Domain.Entities.Report", null)
                        .WithMany()
                        .HasForeignKey("report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.AssetPolicyGroup", b =>
                {
                    b.Navigation("AccessRequests");

                    b.Navigation("Conditions");

                    b.Navigation("HiddenColumns");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.Dataset", b =>
                {
                    b.Navigation("AccessRequests");

                    b.Navigation("Columns");

                    b.Navigation("PolicyGroups");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.User", b =>
                {
                    b.Navigation("AccessRequests");

                    b.Navigation("GroupMemberships");

                    b.Navigation("OwnedGroups");

                    b.Navigation("ReviewedRequests");
                });

            modelBuilder.Entity("DataProvisioning.Domain.Entities.VirtualGroup", b =>
                {
                    b.Navigation("Datasets");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
